const data = {
  products: [
    {
      id: 1,
      slug: 'nike-gree-shirt',
      name: 'Green shirt',
      category: 'Shirts',
      image: '/images/green-shirt.jpg',
      price: 70,
      brand: 'Nike',
      numReviews: 20,
      countInStock: 5,
      description: 'A cool shirt',
    },
    {
      id: 2,
      slug: 'lacoste-black-shirt',
      name: 'Black shirt',
      category: 'Shirts',
      image: '/images/black-shirt.jpg',
      price: 55,
      brand: 'Lacoste',
      numReviews: 23,
      countInStock: 19,
      description: 'A cool shirt',
    },
    {
      id: 3,
      slug: 'under-armour-grey-shirt',
      name: 'Grey shirt',
      category: 'Shirts',
      image: '/images/grey-shirt.jpg',
      price: 53,
      brand: 'Under Armour',
      numReviews: 38,
      countInStock: 14,
      description: 'A cool shirt',
    },
    {
      id: 4,
      slug: 'hm-blue-shirt',
      name: 'Blue shirt',
      category: 'Shirts',
      image: '/images/blue-shirt.jpg',
      price: 54,
      brand: 'H&M',
      numReviews: 25,
      countInStock: 12,
      description: 'A cool shirt',
    },
    {
      id: 5,
      slug: 'adidas-red-shirt',
      name: 'Red shirt',
      category: 'Shirts',
      image: '/images/red-shirt.jpg',
      price: 56,
      brand: 'Adidas',
      numReviews: 40,
      countInStock: 20,
      description: 'A cool shirt',
    },
  ],
};

export default data;